{
    "name": "A&C",
    "author": "PKF Antares",
    "version": "2.0.0",
    "category": "Operations",
    "summary": "Acceptance & Continuance Evaluation",
    "depends": ["base", "mail", "contacts", "crm", "ai_agent_restrict", "engagement_letter"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "security/ac_record_rules.xml",
        "security/crm_ac_record_rules.xml",
        "data/sequence.xml",
        "data/job_position_data.xml",
        "views/tabs/ac_job_position_menu.xml",
        "views/ac_evaluation_views.xml",
        "views/engagement_letter_views_inherit.xml",
        "views/ac_clients_views.xml",
        "views/crm_lead_ac_tab.xml",
        "views/ac_menu.xml",
        "views/tabs/overview.xml",
        "views/tabs/risk_analysis.xml",
        "views/tabs/budget.xml",
        "views/tabs/relationship.xml",
        "views/tabs/media_research.xml",
        "views/tabs/trend_research.xml",
        "views/tabs/risk_panel.xml",
        "views/tabs/team_independence.xml",
        "views/mail_composer_inherit.xml",
        "report/a&c_main_report.xml",
        "data/ac_master_data.xml",
        "data/mail_template_data.xml",
    ],
    "application": True,
    "installable": True,
    "license": "LGPL-3",
    "images": ["static/description/icon.png"],
}
